### ISSUE TITLE
Comandos de informação de usuários do Discord não tem thumbnail na info

### ISSUE THREAD

**Issue by StargazerGb** [Espacorede/Shamash#5]
Pode falar português aqui? Se não foda-se.

**Comment by Tarkoviski** [comment]
Eu compilei aqui e está funcionando normalmente. (」゜ロ゜)」

Mudando de assunto um pouco, eu acho que seria melhor usar DiscordEmbedThumbnail ao invés de DiscordEmbedImage no info. Ficaria mais no estilo do resto deles. https://img.espacore.de/sinfo.png

**Comment by StargazerGb** [comment]
↳Done também
